# -*- coding: utf-8 -*-
"""Lambda_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iFQ3eoiaJurXeh1kdf11WyFtlTB5u91
"""

string= "samsung,'OEM Samsung Washing Machine Pulsator WashplateCap Shipped WithWA48J7700AW, WA48J7700AW/A2, WA48J7700AW/AA',20916,samsung,'OEMSamsungChrome Washing Machine Washplate Pulsator Cap ShippedWith WA52M7750AV,WA52M7750AV/A4, WA52M7750AW, WA52M7750AW/A4',91995,samsung,'SAMSUNGWashing Machine Spring Hanger, DC61-01257M',22970,samsung,'SamsungDC97-17022BAssy Detergent',32959,samsung,'Samsung DC66-00470ADAMPERSHOCK',29981,samsung,'DC64-00519D Samsung WashingMachine Door Lock Washer DryerDishwashe -MP#GH4498 349Y49HBRG9109150',52000,samsung,'SamsungDC97-16991AAssembly Filter',13000"

import re
lis=re.split("(,[0-9]+)",string)
helper_dict={}
for index in range(0,len(lis)-2,2):
  val=int(lis[index+1].strip(','))
  helper_dict[val]=lis[index].strip(',')
for key in sorted(helper_dict):
  print(helper_dict[key],key)